### ISSUE TITLE
Make listing form look like Grand Traverse county

### ISSUE THREAD

**Issue by exbinary** [maebeale/mutual-aid#1]
See screenshots below

[Sample results](https://docs.google.com/spreadsheets/d/1J_hfm7xngFNN2iy2IK8GuEWKHjncfI1buxTdxvhRdA8/edit#gid=0)

- [x] Initial changes to models
- [x] Introduce Location model
- [x] Add `Location` fields into form
- [x] Define initial set of tags
- [x] Wire tags into form
- [x] Add `User` fields into form
- [ ] Make form usable as both an `Ask` and `Offer`
- [ ] Allow user to add new tags
- [ ] Eliminate empty `Location` records
- [ ] Add remaining fields

![Grand Traverse County Mutual Aid — Needs and Offerings Form (1)](https://user-images.githubusercontent.com/8330/78066507-11741c00-7363-11ea-84dd-b8ace329bcef.png)
![Grand Traverse County Mutual Aid — Needs and Offerings Form](https://user-images.githubusercontent.com/8330/78066522-189b2a00-7363-11ea-8862-c0daab410aa3.png)

**Comment by maebeale** [comment]
@exbinary  Maybe the "ask" column could be parallel to the "offer" column ?

**Comment by maebeale** [comment]
@exbinary should we consider using location for city, state, and neighborhood, and maybe move street_address to User ?

**Comment by exbinary** [comment]
Initial work completed for v0.1. Remaining tasks moved to miro.
