### ISSUE TITLE
Logout button not displaying in NavBar.vue

### ISSUE THREAD

**Issue by maebeale** [maebeale/mutual-aid#105]
The DeleteButton component doesn't seem to be loading

**Comment by exbinary** [comment]
Hmm, i might need some help recreating this. On `master`, i'm seeing a working `Logout` button.

<img width="1148" alt="Screen Shot 2020-05-07 at 00 57 57" src="https://user-images.githubusercontent.com/8330/81256323-285efb80-8ffe-11ea-88fa-fbae64c9dff4.png">

**Comment by maebeale** [comment]
Seems to be fixed! Yay!
