### ISSUE TITLE
Log out button is erroring when not on root

### ISSUE THREAD

**Issue by maebeale** [maebeale/mutual-aid#239]
I think it's detecting current request.full_path?

<img width="905" alt="Screen Shot 2020-05-14 at 7 04 46 AM" src="https://user-images.githubusercontent.com/7607813/81927241-52da2700-95b1-11ea-9405-b12bc0fe455a.png">

**Comment by armahillo** [comment]
I'll take a look at this one.

**Comment by maebeale** [comment]
YAY!

**Comment by armahillo** [comment]
OK figured it out! Submitting a PR
