### ISSUE TITLE
Set email options in all envs

### ISSUE THREAD

**Issue by maebeale** [maebeale/mutual-aid#33]
seeds.rb is breaking in prod bc the email settings (triggered by devise) weren't set

<img width="1081" alt="Screen Shot 2020-04-09 at 5 01 27 AM" src="https://user-images.githubusercontent.com/7607813/78877737-5234fa80-7a1f-11ea-8a5b-cf17bf2fdbb4.png">

https://stackoverflow.com/questions/7219732/missing-host-to-link-to-please-provide-host-parameter-or-set-default-url-optio

**Comment by h-m-m** [comment]
I was going to fix this by copying into config/environments/production.rb the line from my other PR, at https://github.com/maebeale/mutual-aid/blob/f09c45ef0d49fe6ae0036128f1544174fb05c0b9/config/environments/test.rb#L50

But then I realized I don't know what the host in the URL for prod should look like. Do you want to set it to `localhost` for now so the links deliberately don't work right yet, or do you have a hostname for prod yet?

**Comment by maebeale** [comment]
hey there, @h-m-m ! i invited you to two heroku apps: staging and prod. my vote would be to set it to an ENV var and we can store it using dotenv that you set up. what do you think?

**Comment by h-m-m** [comment]
That sounds smart!

**Comment by maebeale** [comment]
yay! lmk if you want/need me to add the env vars to the heroku apps themselves.

**Comment by maebeale** [comment]
completed
