### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by grenewode** [maebeale/mutual-aid#84]
Hi @maebeale this is Robin from LAMA.

Adding support for launching the application using docker would make it easier to test the application. 
By providing a `docker-compose.yml` file, it would allow developers to rapidly deploy the application for local testing and evaluation.

- [x] Allow the application to be launched for local testing & development using `docker-compose`
- [ ] Create new user accounts in the testing environment
- [ ] Implement a production-ready `docker-compose` setup that can be used for organizations that are not able to use Heroku

**Comment by grenewode** [comment]
See #85

**Comment by maebeale** [comment]
Thanks @grenewode ! Totally works! (We just tested it with a new collaborator to the project.)

Also, you were right re the Log out button. When we moved the navbar out of Rails and in to Vue, it stopped working. I'll make an issue for that for now.
